Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2018-05, with the labels that each got.

#163 Release 7.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#165 Allow puppetlabs-apache 3.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#164 fixes #23557 - log to syslog by default
  manifests/dispatch_router.pp
  manifests/init.pp
  manifests/params.pp
Labels: Enhancement, Needs testing, Not yet reviewed
