Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2019-12, with the labels that each got.

#220 Use Stdlib::Port where appropriate
  manifests/init.pp
  metadata.json
Labels: Needs testing

#223 remove redundant ProxyPassReverse url
  manifests/reverse_proxy.pp
  spec/classes/foreman_proxy_content__reverse_proxy_spec.rb
Labels: Needs testing

#224 Drop node_server_ca_cert parameter
  manifests/init.pp
Labels: Needs testing

#222 Add initial pulp3 support
  .fixtures.yml
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
  templates/pulpcore-apache.conf.erb
Labels: Enhancement, Needs testing

#225 Install file and container plugins for Pulp 3
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#221 Make dispatch router standalone classes
  manifests/dispatch_router.pp
  manifests/dispatch_router/connector.pp
  manifests/dispatch_router/hub.pp
  manifests/init.pp
Labels: Needs testing, Not yet reviewed
