Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2019-04, with the labels that each got.

#197 Refs #26571 - Add dispatch router auth
  manifests/dispatch_router.pp
  manifests/init.pp
  manifests/params.pp
Labels: Enhancement, Needs testing, Not yet reviewed

#198 Require qpid >= 4.5, allow newest major versions
  metadata.json
Labels: Needs testing, Not yet reviewed

#199 Drop Puppet 4
  .travis.yml
  Gemfile
  metadata.json
Labels: Backwards incompatible, Needs testing

#200 Release 9.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, Not yet reviewed

#201 [CP] Picks for Katello 3.10.1
  manifests/dispatch_router.pp
  manifests/init.pp
  manifests/params.pp
  metadata.json
Labels: Needs testing, Not yet reviewed
