Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2020-12, with the labels that each got.

#298 Move static defaults from params to init
  manifests/init.pp
  manifests/params.pp
Labels: Needs testing

#297 Refs #30436 - add import/export params
  manifests/init.pp
  metadata.json
Labels: Needs testing

#304 Refs #30436 - Add import/export params
  manifests/init.pp
  metadata.json
Labels: Needs testing

#305 Release 14.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#302 Fixes #31435 - Drop ssl_protocol parameter
  manifests/init.pp
Labels: Backwards incompatible, Needs testing

#307 Fixes #31509 - Allow changing node FQDN
  manifests/init.pp
Labels: Needs testing, Not yet reviewed

#308 Simplify reverse proxy definition
  manifests/init.pp
Labels: Needs testing

#301 Fixes #31385 - Default to strict qpid-router ciphers
  manifests/init.pp
Labels: Needs testing

#309 Drop parent_fqdn in favor of deriving from foreman_url
  lib/puppet/functions/foreman_proxy_content/host_from_url.rb
  manifests/init.pp
  spec/functions/foreman_proxy_content/host_from_url_spec.rb
Labels: Backwards incompatible, Needs testing

#310 enable pulpcore deb only if enabled
  manifests/init.pp
Labels: Bug, Needs testing
