Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2020-10, with the labels that each got.

#282 deploy pub_dir also when not deploying pulp2
  manifests/init.pp
  manifests/pub_dir.pp
  spec/classes/foreman_proxy_content_spec.rb
  templates/httpd_pub.erb
Labels: Needs re-review, Needs testing

#287 Deploy Apache certificates for standalone Pulpcore
  manifests/init.pp
Labels: Needs testing

#286 Set reverse proxy servername via certs
  manifests/init.pp
  manifests/reverse_proxy.pp
  spec/classes/foreman_proxy_content__reverse_proxy_spec.rb
Labels: Enhancement, Needs testing

#289 Switch to GH Actions from Travis
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  .travis.yml
Labels: Needs testing, skip-changelog

#290 Release 14.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
