Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2020-05, with the labels that each got.

#253 Modulesync: Require voxpupuli-test 1.4
  Gemfile
  Rakefile
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#254 Refs #29211: Use extlib 5.x for EL8 support
  metadata.json
Labels: Needs testing

#252 Fixes #29589 - Ensure pulpcore before proxy
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#251 Refs #29214: Only install Pulp and Qpid on El7
  manifests/init.pp
Labels: Needs testing

#255 Fixes #29214: Add EL8 support to metadata
  metadata.json
  spec/classes/foreman_proxy_content__broker_spec.rb
  spec/classes/foreman_proxy_content__pub_dir_spec.rb
  spec/classes/foreman_proxy_content__reverse_proxy_spec.rb
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs re-review, Needs testing

#257 Allow EL8 supported versions of dependencies
  metadata.json
Labels: Enhancement

#259 Release 11.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
