Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2020-06, with the labels that each got.

#260 Fixes #29660 - Serve Pulpcore ISO via HTTPS
  manifests/init.pp
Labels: Needs testing

#261 Refs #30023: Enable Pulpcore RPM plugin
  manifests/init.pp
  manifests/params.pp
  templates/pulpcore-yum-apache.conf.erb
Labels: Needs testing

#263 Fixes #30059 - Add config for protected content
  manifests/init.pp
  templates/pulpcore-content-apache.conf.erb
  templates/pulpcore-isos-apache.conf.erb
  templates/pulpcore-yum-apache.conf.erb
Labels: Needs testing

#266 Fixes #30217 - configure pulpcore db name
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing, Not yet reviewed

#267 Use the correct variables in pulpcore templates
  templates/pulpcore-api-apache.conf.erb
  templates/pulpcore-content-apache.conf.erb
Labels: Needs testing

#265 Fixes #30211 - don't disable pulp2 plugins when pulpcore disabled
  manifests/init.pp
Labels: Bug, Needs testing

#269 Release 11.1.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
