Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2020-11, with the labels that each got.

#291 Complete Github Actions migration
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  Gemfile
Labels: Needs testing

#293 Deploy reverse proxy in Pulp 3 only scenarios
  manifests/init.pp
Labels: Needs testing

#294 Fix missing variable scoping on reverse_proxy and add tests for pulpcore
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#292 Proxy pulp/deb to pulpcore support
  manifests/init.pp
  manifests/params.pp
  metadata.json
Labels: Enhancement, Needs testing

#300 Don't enable Pulp2 Deb with Pulpcore
  manifests/init.pp
Labels: Bug, Needs testing
