Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2020-02, with the labels that each got.

#237 Refs #28904 - configure pulpcore django_remote_user
  manifests/init.pp
Labels: Enhancement, Needs testing

#240 Fixes #28983 - Allow integers for $proxy_pass_params
  manifests/reverse_proxy.pp
Labels: Bug, Needs testing

#238 Refs #28720 - connect to mongo for content migrations
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#242 Release 10.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#241 Refs #28901 - support external postgres database in pulpcore
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#244 Fixes #28901 - Support SSL connection for external Pulpcore PostgreSQL…
  manifests/init.pp
  manifests/params.pp
  metadata.json
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing
