Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2021-04, with the labels that each got.

#340 Generalize Puppet certs chaining
  .fixtures.yml
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#339 Refs #32239 - Drop pulp 2 parameters from foreman_proxy::plugin::pulp
  manifests/init.pp
  metadata.json
Labels: Needs testing

#341 Allow puppet-qpid 8+
  metadata.json
Labels: Needs testing

#329 Refs #32037: Add flag to enable katello_agent infrastructure and disable it by default
  manifests/dispatch_router.pp
  manifests/init.pp
  metadata.json
  spec/acceptance/dispatch_router_spec.rb
  spec/setup_acceptance_node.pp
Labels: Backwards incompatible, Needs testing

#342 Fixes #32338 - expose pulpcore allowed_content_checksums
  manifests/init.pp
  metadata.json
  spec/classes/foreman_proxy_content_spec.rb
Labels: Enhancement, Needs testing

#343 Fixes #32160 - enable ansible content
  manifests/init.pp
Labels: Enhancement, Needs testing

#346 Refs #32338 - Move content array param to params.pp
  manifests/init.pp
  manifests/params.pp
Labels: Bug, Needs testing

#348 Allow puppet-certs < 13.0.0
  metadata.json
Labels: Enhancement, Needs testing

#345 Release 18.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#349 Fixes #32443 - Add support for md5 for ALLOWED_CONTENT_CHECKSUM
  manifests/params.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Bug, Needs testing

#344 Improve clarity of content type feature param documentation strings
  manifests/init.pp
Labels: Enhancement

#351 Release 18.1.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#352 Use foreman::repo to configure repositories in acceptance
  spec/setup_acceptance_node.pp
Labels: Needs testing

#353 Include certs::foreman_proxy instead of declaring
  manifests/init.pp
Labels: Needs testing
