Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2021-01, with the labels that each got.

#311 include all pulpcore plugins conditionally
  manifests/init.pp
Labels: Enhancement, Needs testing, Waiting on contributor

#312 Add inline note about why certguard is required in all cases
  manifests/init.pp
Labels: Needs testing

#314 Release 14.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#315 Fixes #31662: Set enable_http to ensure pub dir is deployed to Pulp v…
  manifests/init.pp
Labels: Needs testing

#316 Ensure foreman_proxy::plugin::pulp does not enable Pulp 2 on EL8
  manifests/init.pp
Labels: Needs testing

#320 Allow puppet-foreman_proxy 17.0.0
  metadata.json
Labels: Needs testing
