Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2021-03, with the labels that each got.

#328 Fixes #31868: Switch to /pulp/content/ by default for clients
  lib/puppet/provider/rhsm_reconfigure_script/rhsm_reconfigure_script.rb
  spec/acceptance/bootstrap_rpm_spec.rb
Labels: Enhancement, Needs testing

#332 Allow katello/qpid 7.x
  metadata.json
Labels: Needs testing

#330 Update Github Actions workflow
  .github/workflows/acceptance.yml
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  Gemfile
Labels: Modulesync, Needs testing, Not yet reviewed

#334 Release 17.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#336 Pin camptocamp/systemd to 2.12.0 in testing
  .fixtures.yml
Labels: Needs testing

#337 Fixes #32161: Set disablereuse=on and retry=0 on reverse proxy
  manifests/reverse_proxy.pp
  spec/classes/foreman_proxy_content__reverse_proxy_spec.rb
Labels: Needs testing

#331 Add pulpcore_django_secret_key parameter
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#335 Fixes #32149 - Expose pulpcore-{content,api} gunicorn worker timeouts
  manifests/init.pp
  manifests/params.pp
  metadata.json
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#338 Release 17.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
