Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2021-07, with the labels that each got.

#373 Allow puppet-pulpcore 4.0.0
  metadata.json
Labels: Needs testing

#372 Fixes #32910: Support enabling content caching for Pulp
  manifests/init.pp
  metadata.json
Labels: Needs testing

#371 Refs #32891 - Optionally enable new Pulpcore tasking system
  manifests/init.pp
  manifests/params.pp
Labels: Needs testing, Not yet reviewed

#376 Refs #32891 - Fixup param doc
  manifests/init.pp
Labels: Needs testing

#374 Bump version to 20.0.0
  metadata.json
Labels: Needs testing

#377 Release 19.0.0
  CHANGELOG.md
Labels: Needs testing

#379 Allow puppet-pulpcore 5.0.0
  metadata.json
Labels: Enhancement, Needs testing

#380 Release 20.0.0
  CHANGELOG.md
Labels: Needs testing
