Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2021-05, with the labels that each got.

#354 Allow Puppet 7 compatible versions of mods
  metadata.json
Labels: Needs testing, Not yet reviewed

#355 Fixes #32529: Find latest bootstrap RPM by sorting as intenger
  lib/puppet/provider/bootstrap_rpm/bootstrap_rpm.rb
  spec/acceptance/bootstrap_rpm_spec.rb
Labels: Needs testing

#350 Fixes #32383: Set Pulp to expect Foreman host as the client authentic…
  manifests/init.pp
  metadata.json
  spec/classes/foreman_proxy_content_spec.rb
Labels: Enhancement, Needs testing

#357 Fixes #32567: Ensure bootstrap RPM symlink exists
  lib/puppet/provider/bootstrap_rpm/bootstrap_rpm.rb
  lib/puppet/type/bootstrap_rpm.rb
  spec/acceptance/bootstrap_rpm_spec.rb
Labels: Needs testing

#358 Release 18.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed

#359 Switch to voxpupuli-acceptance-1.0
  Gemfile
  spec/acceptance/bootstrap_rpm_spec.rb
  spec/acceptance/dispatch_router_spec.rb
  spec/spec_helper_acceptance.rb
Labels: Needs testing
