Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2021-02, with the labels that each got.

#317 Release 15.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs re-review, Needs testing, skip-changelog

#322 Fixes #31800 - Create qdrouter inbound link for katello.agent queue
  manifests/dispatch_router/hub.pp
Labels: Needs testing

#321 Refs #30360: Disable Pulp 2 foreman_proxy plugin
  manifests/init.pp
Labels: Needs testing

#323 Configure qpid dispatch router on EL8
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#325 Group together spec tests
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing

#319 Fixes #31642 - Add container gateway support
  manifests/container.pp
  manifests/init.pp
  metadata.json
  spec/classes/foreman_proxy_content__container_spec.rb
  templates/container-gateway-fragment.epp
Labels: Enhancement, Needs testing

#324 Release 16.0.0
  CHANGELOG.md
Labels: Needs testing

#327 Refs #31878: Use client certificate auth to talk from qpid-dispatch t…
  manifests/dispatch_router.pp
  manifests/dispatch_router/connector.pp
  manifests/dispatch_router/hub.pp
  manifests/init.pp
  metadata.json
Labels: Backwards incompatible, Enhancement
