Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2021-06, with the labels that each got.

#363 Unpin camptocamp/systemd in fixtures
  .fixtures.yml
Labels: Needs testing

#362 Add explicit dependency on puppet/trusted_ca
  metadata.json
Labels: Bug, Needs testing

#364 Mark compatible with puppet/trusted_ca 4.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#333 Support Puppet 7
  metadata.json
Labels: Enhancement, Needs testing, Not yet reviewed

#365 Fixes #32700: Only capture bootstrap RPMs by name
  lib/puppet/provider/bootstrap_rpm/bootstrap_rpm.rb
Labels: Bug, Needs testing

#356 Fixes #32553 - Remove md5 from allowed content types
  manifests/params.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Enhancement, Needs testing

#366 Release 18.3.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#369 Allow puppet-foreman_proxy 19.0.0
  metadata.json
Labels: Needs testing

#367 Bump to 19.0.0
  metadata.json
Labels: Needs testing, Not yet reviewed

#361 Drop Puppet 5 support
  metadata.json
Labels: Backwards incompatible, Needs testing

#360 Allow certs 14.0.0
  metadata.json
Labels: Needs testing

#368 Set client_authentication on foreman_proxy::plugin::pulp
  manifests/init.pp
  metadata.json
Labels: Needs testing

#370 Allow puppet-qpid 9.0.0
  metadata.json
Labels: Enhancement, Needs testing
