Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2022-01, with the labels that each got.

#394 Pin rdoc to < 6.4
  Gemfile
Labels: Not yet reviewed, Needs testing, skip-changelog

#393 Fixes #34154 - Refresh on Pulp plugin installation
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Needs testing, Bug

#395 Refs #34325 - enable redis cache by default
  manifests/init.pp
Labels: Needs testing
