Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2022-02, with the labels that each got.

#396 use katello::repo to setup katello repo for tests
  .fixtures.yml
  spec/setup_acceptance_node.pp
Labels: Not yet reviewed, Needs testing

#397 Allow katello/certs 15.x
  metadata.json
Labels: Not yet reviewed, Needs testing

#398 Allow theforeman/foreman_proxy 21.x
  metadata.json
Labels: Not yet reviewed, Needs testing

#399 Require at least certs 15
  metadata.json
Labels: Needs testing

#400 Fixes #34406 - drop support for ancient EL versions
  lib/puppet/provider/rhsm_reconfigure_script/rhsm_reconfigure_script.rb
Labels: Needs testing

#401 Release 20.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
