Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2023-09, with the labels that each got.

#455 Remove katello-agent
  manifests/dispatch_router.pp
  manifests/dispatch_router/connector.pp
  manifests/dispatch_router/hub.pp
  manifests/init.pp
  manifests/params.pp
  spec/acceptance/content_standalone_mirror_spec.rb
  spec/acceptance/content_with_foreman_spec.rb
  spec/acceptance/dispatch_router_spec.rb
Labels: Backwards incompatible

#458 Fixes #36709 - Set ANSIBLE_PERMISSION_CLASSES to empty list
  manifests/init.pp
  metadata.json
Labels: Enhancement

#459 Release 25.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
