Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2024-05, with the labels that each got.

#480 enforce xz compression for consumer rpm
  lib/puppet/provider/bootstrap_rpm/bootstrap_rpm.rb
  spec/acceptance/bootstrap_rpm_spec.rb
Labels: Bug

#482 Mark compatible with katello/certs 18.x
  metadata.json
Labels: Not yet reviewed, Enhancement

#483 Mark compatible with theforeman/foreman_proxy 26.x
  metadata.json
Labels: Enhancement

#484 Release 28.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
