Repository theforeman/puppet-foreman_proxy_content, pull requests merged in 2024-01, with the labels that each got.

#468 do not install katello-debug by default
  manifests/init.pp
  spec/classes/foreman_proxy_content_spec.rb
Labels: Enhancement

#469 Support EL9
  metadata.json
  spec/setup_acceptance_node.pp
Labels: Enhancement

#470 Refs #37062 - Use pulpcore::analytics instead of pulpcore::telemetry
  manifests/init.pp
Labels: Backwards incompatible

#471 Fixes #37130 - set owner, group and mode for bootstrap RPM
  lib/puppet/type/bootstrap_rpm.rb
  lib/puppet/type/rhsm_reconfigure_script.rb
  manifests/bootstrap_rpm.pp
  spec/acceptance/bootstrap_rpm_spec.rb
Labels: Bug
